name: deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run scripts in server
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/chatting-practice
            git reset --hard
            git pull origin main
            yarn 
            yarn build
            pm2 reload client
            pm2 reload server
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}